### ISSUE TITLE
Error building metagenome index

### ISSUE THREAD

**Issue by jagos01** [GraceAHall/NanoMAP#1]
Hello,
I would like to classify some nanopore reads with nanoMAP.  I download a few reference genomes to build a small test database.  As seen below, the taxonomy and metagenome are created but indexing the metagenome fails.  Any help would be appreciated.
Thanks,
Scott 

1. building taxonomy
15 files to process
taxonomy built

2. creating metagenome
15 files to concatenate
metagenome created.

3. building metagenome index
Traceback (most recent call last):
  File "build_database.py", line 51, in <module>
    main(sys.argv[1:])
  File "build_database.py", line 28, in main
    build_minimap2_index(context)
  File "build_database.py", line 42, in build_minimap2_index
    ib.build()
  File "/home/test/NanoMAP/DatabaseClasses/IndexBuilder.py", line 18, in build
    self.build_index()
  File "/home/test/NanoMAP/DatabaseClasses/IndexBuilder.py", line 61, in build_index
    subprocess.call(f'minimap2 --idx-no-seq -x map-ont -I {str(ct.max_memory)}G, -t {ct.threads} -d {ct.database_path}database.mmi {ct.database_path}database.fastaaaa', shell=True)
AttributeError: 'DatabaseBuildingContext' object has no attribute 'max_memory'

**Comment by GraceAHall** [comment]
Hi Scott! 

I think I know what the issue is. I'll write a patch tomorrow morning :) 
I'll reply again when the repo has been updated - just pull the repo again to receive the update on your local version! 

Grace

**Comment by jagos01** [comment]
Thanks Grace,
I will wait for the repo to be updated.  I also tried to build a much larger database (19000 genomes) which resulted in the same error as above but also failed to concatenate the fasta files to create the metagenome.  How many genomes can be used to create the metagenome?
Thanks again,
Scott

**Comment by GraceAHall** [comment]
That should have fixed it! Try pulling it again. 

In terms of metagenome size, its not limited to any amount. As long as you have enough storage, you can make any size. 

That said, the process of making a database chews space for something that large. Here is how much storage it would take (ill assume some file sizes here): 

Your genome folder has 19000 genomes - I'm guessing these are bacterial so I think this is around 80gb
The metagenome is a temporary copy of these files. Another 80gb.
The index produced by this metagenome would be around 130gb. 
The metagenome is then deleted. 

By my count, your peak storage usage for a 80gb folder would be roughly 300gb. The final size would be around 220gb. 

Grace

**Comment by jagos01** [comment]
Hello Grace,
Thank you for your help.  I have successfully built my small test database and processed a couple samples.  In regards to my large database, there seems to be an issue in creating the metagenome as seen is step 2 of the database build.  Although a .mmi file was created, it is only 131kb.  Below are the outputs for build_database.py  and nanoMAP.py:

2. creating metagenome
19523 files to concatenate
/bin/sh: 1: cat: Argument list too long
metagenome created.

3. building metagenome index
[M::mm_idx_gen::0.001*2.95] collected minimizers
[M::mm_idx_gen::0.001*2.80] sorted minimizers
[M::main::0.003*2.00] loaded/built the index for 0 target sequence(s)
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 0
[M::mm_idx_stat::0.003*1.98] distinct minimizers: 0 (-nan% are singletons); average occurrences: -nan; average spacing: -nan
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 --idx-no-seq -x map-ont -I 128G, -t 3 -d /home/data0/nanoMAP_db/ncbi-genomes-2020-12-07_RefSeq_compete_genomes/database.mmi /home/data0/nanoMAP_db/ncbi-genomes-2020-12-07_RefSeq_compete_genomes/database.fastaaaa
[M::main] Real time: 0.003 sec; CPU: 0.006 sec; Peak RSS: 0.002 GB
index created.

finished database build.



NanoMAP parameters:
database_path : /home/data0/nanoMAP_db/ncbi-genomes-2020-12-07_RefSeq_compete_genomes/
fastq_path : /home/DRDC/data1/Analyzed_data/Guppy_v4.0.14/HAC_basecalling/results_2020_8_25_16_37_15/barcode/combined/barcode03_combined.fastq
project_path : projects/full_test
project_name : full_test
threads : 4
max_memory : 128
dump_index : True
read_technology : map-ont
include_plasmids_mitochondria : False


=========== Full Database Alignment ===========
running minimap2 on full database
[M::main::0.002*1.90] loaded/built the index for 0 target sequence(s)
[M::mm_mapopt_update::0.002*1.86] mid_occ = 1
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 0
[M::mm_idx_stat::0.002*1.84] distinct minimizers: 0 (-nan% are singletons); average occurrences: -nan; average spacing: -nan
[M::worker_pipeline::1.741*2.84] mapped 21857 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -x map-ont -I 128G -t 4 /home/data0/nanoMAP_db/ncbi-genomes-2020-12-07_RefSeq_compete_genomes/database.mmi /home/DRDC/data1/Analyzed_data/Guppy_v4.0.14/HAC_basecalling/results_2020_8_25_16_37_15/barcode/combined/barcode03_combined.fastq
[M::main] Real time: 1.742 sec; CPU: 4.947 sec; Peak RSS: 0.169 GB


=========== Strain Grouping ===========
calculating classification co-occurence
creating strain group reference metagenomes
binning reads from input fasta

strain group     sample proportion


=========== Identifying Strains ===========

================================================== Final Composition ===================================================
                                                                                         strain name    sample abundance

Any help on building larger indexes would be appreciated.
Thanks,
Scott

**Comment by jagos01** [comment]
Hello Grace, 
I am able to cat the files in my database directory and build the index using the commands below.  The index is now 122.9mb as you estimated. 

cat * > database.fastaaaa

minimap2 --idx-no-seq -x map-ont -I 128G, -t 3 -d /home/data0/nanoMAP_db/ncbi-genomes-2020-12-07_RefSeq_compete_genomes/database.mmi /home/data0/nanoMAP_db/ncbi-genomes-2020-12-07_RefSeq_compete_genomes/database.fastaaaa

Thanks,
Scott

**Comment by jagos01** [comment]
Hello Grace,
I no longer have to build the database and index as in my previous post.  I was able to get build_database.py script to work on my larger database by changing line 50 to:

       subprocess.call(f"find {ct.database_path} -name '*.{ext}' -print0 | xargs -0 cat >> {ct.database_path}database.fastaaaa", shell=True)
Thanks,
Scott

**Comment by GraceAHall** [comment]
Thank you Scott! 

This is a great solution.  I will incorporate it into the code body.
I will add a comment to this line of code crediting you as the author. 

Thanks again for all your help testing and improving NanoMAP during its early stages! 

I am currently working on the other issues you have raised. 

Grace

**Comment by jagos01** [comment]
Thanks Grace,
I just pulled the latest update.  It looks like the changes to line 50 of index_builder.py were not saved.
Thanks,
Scott

**Comment by jagos01** [comment]
Hello Grace,
I am building a similar database for Centrifuge.  Low-complexity regions in the genomes were masked with dustmasker.  Should the same be done for NanoMap databases?
Thanks,
Scott

**Comment by GraceAHall** [comment]
Hi Scott

Thanks for keeping in touch all this time! Sorry that it takes me a few days to get back to you. 

Unfortunately we can't mask any regions of the genome. Low-complexity regions can still be useful by informing NanoMAP which species are present, and they general make the abundance estimation more accurate. 

NanoMAP uses both the low-complexity and unique regions of genomes during runtime, so unless we took a different approach in the future, we have to leave them in for now.

Grace

**Comment by jagos01** [comment]
Thank you Grace.  I will make sure not to mask low-complexity regions for use with NanoMAP.
