### ISSUE TITLE
identified strains failed

### ISSUE THREAD

**Issue by jagos01** [GraceAHall/NanoMAP#2]
Hello Grace,
I am classifying reads from a few projects. I worked great while the other two failed.
1. Case 1 - Sequenced strain is not in database resulted in the following error:

Group 6

narrowing strain candidates:

[M::mm_idx_gen::0.521*1.03] collected minimizers
[M::mm_idx_gen::0.607*1.45] sorted minimizers
[M::main::0.607*1.45] loaded/built the index for 4 target sequence(s)
[M::mm_mapopt_update::0.633*1.43] mid_occ = 43
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 4
[M::mm_idx_stat::0.651*1.42] distinct minimizers: 1137753 (7.76% are singletons); average occurrences: 2.349; average spacing: 5.369
ERROR: failed to open file 'projects/full_test/runtimefiles/group_fastqs/strain_group_6.fq'
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -c -p 0.1 --no-long-join -N 10 -x map-ont -I 128G -t 4 -I 1000G projects/full_test/runtimefiles/group_databases/strain_group_6_initial.fa projects/full_test/runtimefiles/group_fastqs/strain_group_6.fq
[M::main] Real time: 0.660 sec; CPU: 0.932 sec; Peak RSS: 0.516 GB
Traceback (most recent call last):
  File "nanoMAP.py", line 129, in <module>
    main(sys.argv[1:])
  File "nanoMAP.py", line 32, in main
    identified_strains = identify_sample_strains(strain_groups, context)
  File "nanoMAP.py", line 77, in identify_sample_strains
    identified_strains += characterise_group(group, context)
  File "nanoMAP.py", line 91, in characterise_group
    return ga.analyse_group()
  File "/home/NanoMAP/GroupClasses/GroupAnalysis.py", line 32, in analyse_group
    self.process_paf()
  File "/home/NanoMAP/GroupClasses/GroupAnalysis.py", line 66, in process_paf
    self.alignments, self.collinearities = pp.process()
  File "/home/NanoMAP/GroupClasses/PafProcessing.py", line 20, in process
    alignments = self.load_alignments()
  File "/home/NanoMAP/GroupClasses/PafProcessing.py", line 56, in load_alignments
    avg_collinearity = sum([al[2] for al in alignments]) / len(alignments)
ZeroDivisionError: division by zero

*** I checked in the projects folder and projects/full_test/runtimefiles/group_fastqs/strain_group_6.fq does not exist but /projects/full_test/runtimefiles/group_databases/strain_group_6_initial.fa does.

2. Case 2 - Mix of bacterial gDNA/plasmids gave the following error when narrowing strain canditates:

project_path : projects/gDNA_Plasmid
project_name : gDNA_Plasmid
threads : 60
max_memory : 128
dump_index : True
read_technology : map-ont
include_plasmids_mitochondria : False

=========== Full Database Alignment ===========
running minimap2 on full database
[M::main::96.108*0.99] loaded/built the index for 39948 target sequence(s)
[M::mm_mapopt_update::101.912*0.99] mid_occ = 4313
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 39948
[M::mm_idx_stat::106.113*0.99] distinct minimizers: 234873681 (12.11% are singletons); average occurrences: 63.516; average spacing: 5.352
[M::worker_pipeline::307.153*37.33] mapped 76805 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -x map-ont -I 128G -t 60 /home/data0/nanoMAP_db/ncbi-genomes-2020-12-07_RefSeq_compete_genomes/database.mmi /home/data1/Analyzed_data/gDNA_Plasmid/basecall_combined.fastq
[M::main] Real time: 314.137 sec; CPU: 11473.364 sec; Peak RSS: 160.333 GB

=========== Strain Grouping ===========
calculating classification co-occurence
creating strain group reference metagenomes
binning reads from input fasta

strain group     sample proportion
          25                26.85%
           0                23.44%
          15                 3.32%
           1                 3.14%
          23                 3.04%
          20                 1.88%
           2                 1.86%
           6                 1.84%
           5                 1.84%
           7                 1.83%
           3                 1.83%
           4                 1.83%
           8                 1.83%
          12                 1.80%
           9                 1.80%
          11                 1.80%
          10                 1.79%
          13                 1.79%
          19                 1.77%
          38                 1.63%
          16                 0.94%
          17                 0.93%
          14                 0.91%
          21                 0.80%
         141                 0.53%
          64                 0.52%
         124                 0.47%
          24                 0.23%

=========== Identifying Strains ===========

Group 25

narrowing strain candidates:

[M::mm_idx_gen::0.186*1.12] collected minimizers
[M::mm_idx_gen::0.215*2.22] sorted minimizers
[M::main::0.215*2.22] loaded/built the index for 4 target sequence(s)
[M::mm_mapopt_update::0.234*2.12] mid_occ = 8
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 4
[M::mm_idx_stat::0.250*2.05] distinct minimizers: 916003 (97.69% are singletons); average occurrences: 1.034; average spacing: 5.350
[M::worker_pipeline::0.320*8.96] mapped 538 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -c -p 0.1 --no-long-join -N 10 -x map-ont -I 128G -t 60 -I 1000G projects/gDNA_Plasmid/runtimefiles/group_databases/strain_group_25_initial.fa projects/gDNA_Plasmid/runtimefiles/group_fastqs/strain_group_25.fq
[M::main] Real time: 0.333 sec; CPU: 2.876 sec; Peak RSS: 0.658 GB
0 strains are extrachromosomal dominant

                                                        name                                                    filename   naive abund.   MAPQ_60   MAPQ_10    MAPQ_2    MAPQ_1

identified strains:

Single strain detected in group. Setting sample abundance
Traceback (most recent call last):
  File "nanoMAP.py", line 129, in <module>
    main(sys.argv[1:])
  File "nanoMAP.py", line 32, in main
    identified_strains = identify_sample_strains(strain_groups, context)
  File "nanoMAP.py", line 77, in identify_sample_strains
    identified_strains += characterise_group(group, context)
  File "nanoMAP.py", line 91, in characterise_group
    return ga.analyse_group()
  File "/home/DRDC/NanoMAP/GroupClasses/GroupAnalysis.py", line 49, in analyse_group
    self.estimate_abundances()
  File "/home/DRDC/NanoMAP/GroupClasses/GroupAnalysis.py", line 112, in estimate_abundances
    self.identified_strains = pe.estimate()
  File "/home/DRDC/NanoMAP/AbundanceClasses/ProportionEstimator.py", line 31, in estimate
    self.set_simple_abundance()
  File "/home/DRDC/NanoMAP/AbundanceClasses/ProportionEstimator.py", line 196, in set_simple_abundance
    self.present_strains[0].sample_abundance = self.group_abundance
IndexError: list index out of range

 Any help would be appreciated.
Thanks,
Scott

**Comment by GraceAHall** [comment]
Thanks again! I can see what the issues are. 

I have some time tomorrow, so will fix this problem :) 
Thank you for being so patient, and helping my iron out some release bugs! 

Grace

**Comment by jagos01** [comment]
Hello Grace,
I tried to classify anther set of reads.  I received the same error as in #1 above (ZeroDivisionError: division by zero).
I will wait for an update to be pushed.
Thanks,
Scott

**Comment by GraceAHall** [comment]
Hi Scott, 

I think I may have solved these issues now. Sorry was quite a busy week. 
Try pulling the new version (v1.1) and let me know if its all ok! 

Grace

**Comment by jagos01** [comment]
Hello Grace,
Thank you for this program and your time assisting me.  I ran v1.1 on a metagenomic sample. I do not believe all the strains were in the database I built.  Below is the error that was returned:

group 7 narrowing done.

Group 2

narrowing strain candidates:

[M::mm_idx_gen::1.260*1.61] collected minimizers
[M::mm_idx_gen::1.400*2.15] sorted minimizers
[M::main::1.400*2.15] loaded/built the index for 14 target sequence(s)
[M::mm_mapopt_update::1.500*2.07] mid_occ = 24
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 14
[M::mm_idx_stat::1.570*2.03] distinct minimizers: 5221202 (88.03% are singletons); average occurrences: 1.180; average spacing: 5.351
[M::worker_pipeline::49.944*36.93] mapped 88086 sequences
[M::worker_pipeline::67.548*36.54] mapped 41098 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -c -p 0.1 --no-long-join -N 10 -x map-ont -I 128G -t 40 -I 1000G projects/ATCC_gDNA_plasmid_mix/runtimefiles/group_databases/strain_group_2_initial.fa projects/ATCC_gDNA_plasmid_mix/runtimefiles/group_fastqs/strain_group_2.fq
[M::main] Real time: 67.729 sec; CPU: 2468.476 sec; Peak RSS: 34.882 GB
0 strains are extrachromosomal dominant


                                                        name                                                    filename   naive abund.   MAPQ_60   MAPQ_10    MAPQ_2    MAPQ_1
                  Yersinia frederiksenii strain FDAARGOS_418                     GCF_002591195.1_ASM259119v1_genomic.fna          82.82     60059     63893     64188     66190
                                  Yersinia rohdei strain YRA                      GCF_000834455.1_ASM83445v1_genomic.fna           6.58       589       973      1030      2030
                                Yersinia enterocolitica LC20                      GCF_000597945.1_ASM59794v2_genomic.fna           5.61       146       256       287       858
                         Yersinia canariae strain NCTC 14382                     GCF_009831415.1_ASM983141v1_genomic.fna           4.93       953      1094      1112      1422
                                Citrobacter sp. RHBSTW-00127                    GCF_013791465.1_ASM1379146v1_genomic.fna           0.03         0         1         1         1
                              Escherichia coli strain ST2747                      GCF_000599685.1_ASM59968v1_genomic.fna           0.01         1         1         1         1
                         Edwardsiella tarda strain KC-Pc-HB1                     GCF_002504285.1_ASM250428v1_genomic.fna           0.01         0         0         0         0

selecting 4 strains

Traceback (most recent call last):
  File "nanoMAP.py", line 132, in <module>
    main(sys.argv[1:])
  File "nanoMAP.py", line 32, in main
    identified_strains = identify_sample_strains(strain_groups, context)
  File "nanoMAP.py", line 77, in identify_sample_strains
    strain_abundance_estimates = characterise_group(group, context)
  File "nanoMAP.py", line 94, in characterise_group
    return ga.analyse_group()
  File "/home/NanoMAP/GroupClasses/GroupAnalysis.py", line 38, in analyse_group
    self.halve_candidates()
  File "/home/NanoMAP/GroupClasses/GroupAnalysis.py", line 81, in halve_candidates
    self.characterisation = hv.halve()
  File "/home/NanoMAP/GroupClasses/Halver.py", line 51, in halve
    if characterisation[i].mapq_dict[10] > 2:
IndexError: list index out of range

Thank you again for your help,
Scott

**Comment by GraceAHall** [comment]
Yes I think you are correct. Generally If the correct strain is in the database, that strain will have many MAPQ=60 read alignments, while all others have zero. 

What you could take from this is that you have a yersinia organism. It is most similar to Yersinia frederiksenii, but has some genetic differences to the FDAARGOS_418 strain.  These variants may actually be present in the other organisms, causing those other microbes to display high MAPQ score read alignments. The fact that they possess some local similarity to the sample organism creates the results you see.

I will fix that one up too. NanoMAP does seem to still have a few bugs when the correct strain is not in the reference. I might add an automated check to detect this scenario, and use some other way of reporting information to the user. 

Grace

**Comment by jagos01** [comment]
Thank you.  I will wait for an update to be pushed.
Scott

**Comment by jagos01** [comment]
Hello Grace,
I added the genomes of the bacteria/virus that are present in the above sample to my NCBI RefSeq database.  Several strains were identified before nanoMAP.py ended with the following error:

No strains detected above abundance threshold in group. Continuing for other groups
group 28 narrowing done.
Traceback (most recent call last):
  File "nanoMAP.py", line 132, in <module>
    main(sys.argv[1:])
  File "nanoMAP.py", line 32, in main
    identified_strains = identify_sample_strains(strain_groups, context)
  File "nanoMAP.py", line 79, in identify_sample_strains
    if strain_abundance_estimates[0].sample_abundance > 0:
IndexError: list index out of range
 
Any help would be appreciated.
Thanks,
Scott

**Comment by jagos01** [comment]
Hello Grace,
I ran one more test with a pure isolate.  The isolate was in the RefSeq database.  The correct strain was identified along with  other strains of the same species.  nanoMAP.py returened the following error:

Group 3

narrowing strain candidates:

[M::mm_idx_gen::0.266*1.20] collected minimizers
[M::mm_idx_gen::0.303*2.77] sorted minimizers
[M::main::0.303*2.77] loaded/built the index for 2 target sequence(s)
[M::mm_mapopt_update::0.330*2.62] mid_occ = 23
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 2
[M::mm_idx_stat::0.350*2.53] distinct minimizers: 1086441 (87.64% are singletons); average occurrences: 1.227; average spacing: 5.370
ERROR: failed to open file 'projects/Test_B/runtimefiles/group_fastqs/strain_group_3.fq'
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -c -p 0.1 --no-long-join -N 10 -x map-ont -I 128G -t 40 -I 1000G projects/Test_B/runtimefiles/group_databases/strain_group_3_initial.fa projects/Test_B/runtimefiles/group_fastqs/strain_group_3.fq
[M::main] Real time: 0.359 sec; CPU: 0.894 sec; Peak RSS: 1.638 GB
Traceback (most recent call last):
  File "nanoMAP.py", line 132, in <module>
    main(sys.argv[1:])
  File "nanoMAP.py", line 32, in main
    identified_strains = identify_sample_strains(strain_groups, context)
  File "nanoMAP.py", line 77, in identify_sample_strains
    strain_abundance_estimates = characterise_group(group, context)
  File "nanoMAP.py", line 94, in characterise_group
    return ga.analyse_group()
  File "/home/NanoMAP/GroupClasses/GroupAnalysis.py", line 32, in analyse_group
    self.process_paf()
  File "/home/NanoMAP/GroupClasses/GroupAnalysis.py", line 66, in process_paf
    self.alignments, self.collinearities = pp.process()
  File "/home/NanoMAP/GroupClasses/PafProcessing.py", line 20, in process
    alignments = self.load_alignments()
  File "/home/NanoMAP/GroupClasses/PafProcessing.py", line 56, in load_alignments
    avg_collinearity = sum([al[2] for al in alignments]) / len(alignments)
ZeroDivisionError: division by zero

As minimap2 reported, strain_group3.fq (projects/Test_B/runtimefiles/group_fastqs/strain_group_3.fq) is not present but  strain_group_3_initail.fa (projects/Test_B/runtimefiles/group_databases/strain_group_3_initial.fa) does.
Let me know if you need further information.
Thanks,
Scott

**Comment by GraceAHall** [comment]
Hi Scott :) 

Thanks again for all the input! 
These items should be fixed now. Let me know how it goes! 

Grace

**Comment by jagos01** [comment]
Hello Grace,
Thank you for your help.  With the latest version I was able to successfully run 2 samples from pure cultures.  Two other samples resulted in errors.
The first, which is a mix of 15 isolates, results in the following error: 

Group 608

narrowing strain candidates:

[M::mm_idx_gen::0.148*6.12] collected minimizers
[M::mm_idx_gen::0.173*7.26] sorted minimizers
[M::main::0.173*7.26] loaded/built the index for 3 target sequence(s)
[M::mm_mapopt_update::0.187*6.80] mid_occ = 20
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 3
[M::mm_idx_stat::0.198*6.48] distinct minimizers: 719669 (97.55% are singletons); average occurrences: 1.043; average spacing: 5.346
[M::worker_pipeline::0.201*6.40] mapped 1 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -c -p 0.1 --no-long-join -N 10 -x map-ont -I 128G -t 40 -I 1000G projects/ATCC_gDNA_plasmid_mix.gfast.fulldb/runtimefiles/group_databases/strain_group_608_initial.fa projects/ATCC_gDNA_plasmid_mix.gfast.fulldb/runtimefiles/group_fastqs/strain_group_608.fq
[M::main] Real time: 0.207 sec; CPU: 1.292 sec; Peak RSS: 32.654 GB
Traceback (most recent call last):
  File "nanoMAP.py", line 132, in <module>
    main(sys.argv[1:])
  File "nanoMAP.py", line 32, in main
    identified_strains = identify_sample_strains(strain_groups, context)
  File "nanoMAP.py", line 77, in identify_sample_strains
    strain_abundance_estimates = characterise_group(group, context)
  File "nanoMAP.py", line 94, in characterise_group
    return ga.analyse_group()
  File "/home/NanoMAP/GroupClasses/GroupAnalysis.py", line 33, in analyse_group
    self.process_paf()
  File "/home/NanoMAP/GroupClasses/GroupAnalysis.py", line 69, in process_paf
    self.alignments, self.collinearities = pp.process()
  File "/home/NanoMAP/GroupClasses/PafProcessing.py", line 24, in process
    self.set_thresholds(alignments)
  File "/home/NanoMAP/GroupClasses/PafProcessing.py", line 67, in set_thresholds
    std_dev_collinearity = sum([(al[2] - avg_collinearity) ** 2 for al in alignments]) / (len(alignments) - 1)
ZeroDivisionError: float division by zero


The second is a pure isolate and results in the following error:

multiple identified strains in group
performing composition estimation

preparing reference database
running minimap2 on database
[M::mm_idx_gen::0.156*1.03] collected minimizers
[M::mm_idx_gen::0.175*2.08] sorted minimizers
[M::main::0.175*2.08] loaded/built the index for 2 target sequence(s)
[M::mm_mapopt_update::0.187*2.01] mid_occ = 29
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 2
[M::mm_idx_stat::0.196*1.97] distinct minimizers: 443891 (29.21% are singletons); average occurrences: 1.810; average spacing: 5.346
[M::worker_pipeline::1.084*24.01] mapped 1658 sequences
[M::worker_pipeline::1.480*28.08] mapped 1488 sequences
[M::worker_pipeline::1.973*30.59] mapped 1489 sequences
[M::worker_pipeline::2.551*32.40] mapped 1571 sequences
[M::worker_pipeline::3.006*32.97] mapped 1596 sequences
[M::worker_pipeline::3.442*33.52] mapped 1463 sequences
[M::worker_pipeline::3.901*33.97] mapped 1506 sequences
[M::worker_pipeline::4.497*34.15] mapped 1516 sequences
[M::worker_pipeline::4.932*34.61] mapped 1418 sequences
[M::worker_pipeline::5.339*34.76] mapped 1658 sequences
[M::worker_pipeline::5.903*34.96] mapped 1522 sequences
[M::worker_pipeline::6.320*35.19] mapped 1458 sequences
[M::worker_pipeline::6.908*35.34] mapped 1494 sequences
[M::worker_pipeline::7.372*35.34] mapped 1499 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -c -x map-ont -t 40 -K 50M -I 128G projects/SpoIIa.fl90.fulldb/runtimefiles/abundance_estimation/database.fa /home/data1/SpoIIa.fl90.700mb.fastq
[M::main] Real time: 7.417 sec; CPU: 260.589 sec; Peak RSS: 1.061 GB
running minimap2 on database
[M::mm_idx_gen::0.157*1.03] collected minimizers
[M::mm_idx_gen::0.175*2.19] sorted minimizers
[M::main::0.175*2.19] loaded/built the index for 2 target sequence(s)
[M::mm_mapopt_update::0.187*2.11] mid_occ = 29
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 2
[M::mm_idx_stat::0.196*2.06] distinct minimizers: 443891 (29.21% are singletons); average occurrences: 1.810; average spacing: 5.346
[M::worker_pipeline::0.857*26.83] mapped 6666 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -c -x map-ont -t 40 -K 50M -I 128G projects/SpoIIa.fl90.fulldb/runtimefiles/abundance_estimation/database.fa projects/SpoIIa.fl90.fulldb/runtimefiles/abundance_estimation/fragments.fq
[M::main] Real time: 0.865 sec; CPU: 22.998 sec; Peak RSS: 0.153 GB
EM rounds start
Traceback (most recent call last):
  File "nanoMAP.py", line 132, in <module>
    main(sys.argv[1:])
  File "nanoMAP.py", line 32, in main
    identified_strains = identify_sample_strains(strain_groups, context)
  File "nanoMAP.py", line 77, in identify_sample_strains
    strain_abundance_estimates = characterise_group(group, context)
  File "nanoMAP.py", line 94, in characterise_group
    return ga.analyse_group()
  File "/home/NanoMAP/GroupClasses/GroupAnalysis.py", line 52, in analyse_group
    self.estimate_abundances()
  File "/home/NanoMAP/GroupClasses/GroupAnalysis.py", line 117, in estimate_abundances
    self.identified_strains = pe.estimate()
  File "/home/NanoMAP/AbundanceClasses/ProportionEstimator.py", line 29, in estimate
    self.perform_alignment_based_estimation()
  File "/home/NanoMAP/AbundanceClasses/ProportionEstimator.py", line 64, in perform_alignment_based_estimation
    self.estimate_proportions(empirical_organism_summary, observed_counts)
  File "/home/NanoMAP/AbundanceClasses/ProportionEstimator.py", line 182, in estimate_proportions
    self.sample_proportions, self.data_ll = tem.iterate()
  File "/home/NanoMAP/AbundanceClasses/TerryEM.py", line 81, in iterate
    self.set_final_proportions()
  File "/home/NanoMAP/AbundanceClasses/TerryEM.py", line 202, in set_final_proportions
    self.sample_proportions[symbol] = count / self.total_count
ZeroDivisionError: division by zero

Let me know if your require further informaiton.
Thanks,
Scott
